all: install

install: teste-stack teste-stack0 teste-stack1 teste-stack2 teste-stack3 teste-stack4 teste-stack5 teste-symbol-table teste-symbol-table0 teste-symbol-table1 teste-symbol-table2 teste-symbol-table3 teste-symbol-table4

teste-stack: $(OBJ_DIR)/stack.o $(INC_DIR)/stack.h teste-stack.c
	$(CC) $(CFLAGS) -o teste-stack $(OBJ_DIR)/stack.o \
-I$(INC_DIR) teste-stack.c 

teste-stack0: $(OBJ_DIR)/stack.o $(INC_DIR)/stack.h teste-stack0.c
	$(CC) $(CFLAGS) -o teste-stack0 $(OBJ_DIR)/stack.o \
-I$(INC_DIR) teste-stack0.c

teste-stack1: $(OBJ_DIR)/stack.o $(INC_DIR)/stack.h teste-stack1.c
	$(CC) $(CFLAGS) -o teste-stack1 $(OBJ_DIR)/stack.o \
-I$(INC_DIR) teste-stack1.c

teste-stack2: $(OBJ_DIR)/stack.o $(INC_DIR)/stack.h teste-stack2.c
	$(CC) $(CFLAGS) -o teste-stack2 $(OBJ_DIR)/stack.o \
-I$(INC_DIR) teste-stack2.c

teste-stack3: $(OBJ_DIR)/stack.o $(INC_DIR)/stack.h teste-stack3.c
	$(CC) $(CFLAGS) -o teste-stack3 $(OBJ_DIR)/stack.o \
-I$(INC_DIR) teste-stack3.c

teste-stack4: $(OBJ_DIR)/stack.o $(INC_DIR)/stack.h teste-stack4.c
	$(CC) $(CFLAGS) -o teste-stack4 $(OBJ_DIR)/stack.o \
-I$(INC_DIR) teste-stack4.c

teste-stack5: $(OBJ_DIR)/stack.o $(INC_DIR)/stack.h teste-stack5.c
	$(CC) $(CFLAGS) -o teste-stack5 $(OBJ_DIR)/stack.o \
-I$(INC_DIR) teste-stack5.c  

teste-symbol-table: $(OBJ_DIR)/symbol_table.o $(INC_DIR)/stack.h teste-symbol-table.c
	$(CC) $(CFLAGS) -o teste-symbol-table $(OBJ_DIR)/symbol_table.o \
-I$(INC_DIR) teste-symbol-table.c

teste-symbol-table0: $(OBJ_DIR)/symbol_table.o $(INC_DIR)/stack.h teste-symbol-table0.c
	$(CC) $(CFLAGS) -o teste-symbol-table0 $(OBJ_DIR)/symbol_table.o \
-I$(INC_DIR) teste-symbol-table0.c

teste-symbol-table1: $(OBJ_DIR)/symbol_table.o $(INC_DIR)/stack.h teste-symbol-table1.c
	$(CC) $(CFLAGS) -o teste-symbol-table1 $(OBJ_DIR)/symbol_table.o \
-I$(INC_DIR) teste-symbol-table1.c

teste-symbol-table2: $(OBJ_DIR)/symbol_table.o $(INC_DIR)/stack.h teste-symbol-table2.c
	$(CC) $(CFLAGS) -o teste-symbol-table2 $(OBJ_DIR)/symbol_table.o \
-I$(INC_DIR) teste-symbol-table2.c

teste-symbol-table3: $(OBJ_DIR)/symbol_table.o $(INC_DIR)/stack.h teste-symbol-table3.c
	$(CC) $(CFLAGS) -o teste-symbol-table3 $(OBJ_DIR)/symbol_table.o \
-I$(INC_DIR) teste-symbol-table3.c

teste-symbol-table4: $(OBJ_DIR)/symbol_table.o $(INC_DIR)/stack.h teste-symbol-table4.c
	$(CC) $(CFLAGS) -o teste-symbol-table4 $(OBJ_DIR)/symbol_table.o \
-I$(INC_DIR) teste-symbol-table4.c
    
clean:
	rm -f teste-stack teste-stack0 teste-stack1 teste-stack2 teste-stack3 teste-stack4 teste-stack5 teste-symbol-table teste-symbol-table0 teste-symbol-table1 teste-symbol-table2 teste-symbol-table3 teste-symbol-table4
